spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tushar815/config-repo.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  lifecycle:
    timeout-per-shutdown-phase: 15s

server:
  port: 8888
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 2s
    keep-alive-timeout: 15s
  shutdown: graceful