apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: config-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: [ "sh","-c" ,"sleep 5"]
        ports:
          - containerPort: 8888
        env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: "https://github.com/tushar815/config-repo.git"


